import "./global.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased max-w-5xl mx-auto py-6 px-4 md:py-12 md:px-6 bg-white dark:bg-neutral-950 text-neutral-900 dark:text-neutral-50">
        {children}
      </body>
    </html>
  );
}